export const OllasComunitarias = [
        {Location: 'Dining Room 1',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 2',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 3',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 4',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {Location: 'Dining Room 1',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 2',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 3',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 4',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {Location: 'Dining Room 1',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 2',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 3',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        },
        {
        Location: 'Dining Room 4',
        NumberOfBeneficiaries: 100,
        TeamInCharge: 'Team A',
        Rating: 4.5,
        }
    ]
